name: 'UI compile and deploy'

on: [release]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Fetch repo
      uses: actions/checkout@v2
    - name: Install QT
      uses: jurplel/install-qt-action@v2
